# Generated by Django 4.1.2 on 2022-10-27 08:15

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('preview_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, quality=100, scale=None, size=[370, 266], upload_to='%Y/%M/%D')),
                ('content', ckeditor.fields.RichTextField()),
                ('tags', models.CharField(max_length=300, verbose_name='Тэги')),
                ('category', models.CharField(choices=[('Еда', 'Еда'), ('Красота', 'Красота'), ('Стиль жизни', 'Стиль жизни'), ('Путешествия', 'Путешествия')], max_length=11, verbose_name='Категория')),
            ],
        ),
    ]
