# Generated by Django 4.1.2 on 2022-10-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments_amount',
            field=models.SmallIntegerField(default=0, verbose_name='Количество комментариев'),
        ),
    ]
