# Generated by Django 4.1.3 on 2022-12-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_article_comments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_image',
            field=models.ImageField(upload_to='%Y/%m/%d/', verbose_name='Миниатюора статьи'),
        ),
    ]
