# Generated by Django 4.1.3 on 2023-01-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_alter_article_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=58, verbose_name='Краткое описание'),
        ),
    ]
