# Generated by Django 4.1.2 on 2022-10-31 09:57

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField(verbose_name='Цена')),
                ('category', models.CharField(max_length=40, verbose_name='Категория')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=False, quality=100, scale=None, size=[510, 510], upload_to='<django.db.models.fields.CharField>/')),
                ('amount', models.SmallIntegerField(verbose_name='Количество')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('reviews_amount', models.SmallIntegerField(verbose_name='Количество отзывов')),
                ('rating', models.SmallIntegerField(verbose_name='Оценка')),
                ('weight', models.SmallIntegerField(verbose_name='Вес')),
            ],
        ),
    ]
