# Generated by Django 4.1.2 on 2022-10-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cладости', 'cладости'), ('хлеб и выпечка', 'хлеб и выпечка'), ('хвощи и фрукты', 'овощи и фрукты'), ('мясо и птица', 'мясо и птица'), ('торты и пирожные', 'торты и пирожные'), ('колбасы и сосиски', 'колбасы и сосиски'), ('бакалея', 'бакалея'), ('снеки', 'снеки'), ('напитки', 'напитки')], max_length=40, verbose_name='Категория'),
        ),
    ]
