# Generated by Django 4.1.2 on 2022-11-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_alter_product_image_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cладости', 'cладости'), ('хлеб и выпечка', 'хлеб и выпечка'), ('овощи и фрукты', 'овощи и фрукты'), ('мясо и птица', 'мясо и птица'), ('торты и пирожные', 'торты и пирожные'), ('колбасы и сосиски', 'колбасы и сосиски'), ('бакалея', 'бакалея'), ('снеки', 'снеки'), ('напитки', 'напитки')], max_length=40, verbose_name='Категория')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cладости', 'cладости'), ('хлеб и выпечка', 'хлеб и выпечка'), ('овощи и фрукты', 'овощи и фрукты'), ('мясо и птица', 'мясо и птица'), ('торты и пирожные', 'торты и пирожные'), ('колбасы и сосиски', 'колбасы и сосиски'), ('бакалея', 'бакалея'), ('снеки', 'снеки'), ('напитки', 'напитки')], max_length=40, verbose_name='Категория'),
        ),
    ]
