# Generated by Django 4.1.2 on 2022-11-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_action_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(1, 'cладости'), (2, 'хлеб и выпечка'), (3, 'овощи и фрукты'), (4, 'мясо и птица'), (5, 'торты и пирожные'), (6, 'колбасы и сосиски'), (7, 'бакалея'), (8, 'снеки'), (9, 'напитки')], max_length=40, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'cладости'), (2, 'хлеб и выпечка'), (3, 'овощи и фрукты'), (4, 'мясо и птица'), (5, 'торты и пирожные'), (6, 'колбасы и сосиски'), (7, 'бакалея'), (8, 'снеки'), (9, 'напитки')], verbose_name='Категория'),
        ),
    ]
