# Generated by Django 4.1.2 on 2022-11-02 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
            ],
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category']},
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopApp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveSmallIntegerField(verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product'),
        ),
    ]
