# Generated by Django 4.1.2 on 2022-11-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0009_discounts_delete_action_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Цена со скидкой'),
            preserve_default=False,
        ),
    ]
