# Generated by Django 4.1.2 on 2022-11-04 14:02

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0010_product_discounted_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounts',
            options={'ordering': ['-discount_value']},
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=False, quality=100, scale=None, size=[510, 510], upload_to='shop/'),
        ),
    ]
