# Generated by Django 4.1.2 on 2022-11-08 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0011_alter_discounts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveSmallIntegerField(default=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'), verbose_name='Цена со скидкой'),
        ),
    ]
