# Generated by Django 4.1.2 on 2022-11-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0012_alter_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Размер скидки'),
        ),
    ]
