# Generated by Django 4.1.2 on 2022-11-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0013_product_discount_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, verbose_name='Категория')),
                ('min_price', models.PositiveSmallIntegerField(default=0, verbose_name='Минимальная цена')),
                ('max_price', models.PositiveSmallIntegerField(default=0, verbose_name='Максимальная цена')),
            ],
        ),
    ]
