# Generated by Django 4.1.2 on 2022-11-24 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0015_alter_pricerange_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerange',
            name='min_price',
            field=models.PositiveSmallIntegerField(default=9999999, verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveSmallIntegerField(blank=True, default=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'), verbose_name='Цена со скидкой'),
        ),
    ]
