# Generated by Django 4.1.2 on 2022-11-25 14:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0017_alter_product_discount_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountsTEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('discounted_price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductTEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=False, quality=100, scale=None, size=[510, 510], upload_to='shop/')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('reviews_amount', models.SmallIntegerField(blank=True, default=0, verbose_name='Количество отзывов')),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Оценка')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('Discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopApp.discountstest')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopApp.category')),
            ],
        ),
        migrations.AddField(
            model_name='discountstest',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopApp.producttest'),
        ),
    ]
