# Generated by Django 4.1.2 on 2022-11-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0018_discountstest_producttest_discountstest_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttest',
            name='Discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopApp.discountstest'),
        ),
    ]
