# Generated by Django 4.1.2 on 2022-11-25 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0019_alter_producttest_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttest',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='producttest',
            name='category',
        ),
        migrations.RenameField(
            model_name='discounts',
            old_name='product',
            new_name='rel_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='discounts',
            name='discounted_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopApp.discounts'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Размер скидки'),
        ),
        migrations.DeleteModel(
            name='DiscountsTEST',
        ),
        migrations.DeleteModel(
            name='ProductTEST',
        ),
    ]
