# Generated by Django 4.1.3 on 2022-11-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0022_alter_discounts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='rel_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='shopApp.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopApp.category'),
        ),
    ]
