# Generated by Django 4.1.3 on 2022-11-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0024_alter_discounts_rel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='rel_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='shopApp.product', verbose_name='Продукт'),
        ),
    ]
