# Generated by Django 4.1.3 on 2022-11-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0025_alter_discounts_rel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='rel_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopApp.discounts', verbose_name='Акция'),
        ),
    ]
