# Generated by Django 4.1.3 on 2022-12-03 13:55

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0026_alter_discounts_rel_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounts',
            options={'ordering': ['rel_product__name']},
        ),
        migrations.AlterField(
            model_name='pricerange',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopApp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=False, quality=100, scale=None, size=[1920, 1080], upload_to='shop/'),
        ),
    ]
