# Generated by Django 4.1.3 on 2023-02-21 08:09

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0029_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания действия промокода')),
                ('max_uses', models.IntegerField(default=1, verbose_name='Максимальное количество использований')),
                ('used', models.IntegerField(default=0, verbose_name='Коилчество использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
