# Generated by Django 4.1.3 on 2023-03-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0031_remove_product_reviews_amount_alter_review_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
