# Generated by Django 4.1.3 on 2023-03-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0032_product_image_bytes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
