# Generated by Django 4.1.3 on 2023-03-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0033_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_field',
            field=models.ImageField(blank=True, upload_to='shop/', verbose_name='Картинка'),
        ),
    ]
