# Generated by Django 4.1.3 on 2023-03-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0034_product_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_bytes',
        ),
    ]
