# Generated by Django 4.1.3 on 2023-03-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0035_remove_product_image_bytes'),
    ]

    operations = [
    ]
