# Generated by Django 4.1.3 on 2023-03-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0036_auto_20230306_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_field',
            new_name='image',
        ),
    ]
