# Generated by Django 4.1.3 on 2023-03-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
